//! Actix-owned wrappers for finalized and pending core responses.

use actix_web::{
    HttpRequest, HttpResponse, Responder, body::BoxBody, http::StatusCode as ActixStatusCode,
};
use inertia_core::{CoreBody, CoreResponse, PendingResponse};
use serde::Serialize;
use std::{cell::RefCell, rc::Rc};

const MISSING_MIDDLEWARE: &str = "An Inertia response was returned, but InertiaMiddleware is not installed.\n\nInstall the Actix app data, middleware, and asset configuration shown in inertia_actix::configure.";

/// Actix response containing a finalized framework-neutral response.
pub struct Response(pub CoreResponse);

/// Descriptive alias for a finalized [`Response`].
pub type ActixResponse = Response;

/// Result returned by asynchronous Actix Inertia handlers.
pub type Result = std::result::Result<Response, actix_web::Error>;

impl Responder for Response {
    type Body = BoxBody;

    fn respond_to(self, _request: &HttpRequest) -> HttpResponse<Self::Body> {
        core_response(self.0)
    }
}

pub(crate) fn core_response(response: CoreResponse) -> HttpResponse<BoxBody> {
    let (status, headers, body) = response.into_parts();
    let status = ActixStatusCode::from_u16(status.as_u16())
        .expect("framework-neutral core emitted a valid HTTP status");
    let mut builder = HttpResponse::build(status);
    for (name, value) in &headers {
        let name = actix_web::http::header::HeaderName::from_bytes(name.as_str().as_bytes())
            .expect("framework-neutral core emitted a valid HTTP header name");
        let value = actix_web::http::header::HeaderValue::from_bytes(value.as_bytes())
            .expect("framework-neutral core emitted a valid HTTP header value");
        builder.append_header((name, value));
    }
    match body {
        CoreBody::Empty => builder.finish(),
        CoreBody::Bytes(bytes) => builder.body(bytes),
    }
}

/// Request-local one-shot pending response stored in an Actix response extension.
#[derive(Clone)]
pub(crate) struct PendingResponseHandle(Rc<RefCell<Option<PendingResponse>>>);

impl PendingResponseHandle {
    pub(crate) fn new(pending: PendingResponse) -> Self {
        Self(Rc::new(RefCell::new(Some(pending))))
    }

    pub(crate) fn take(&self) -> Option<PendingResponse> {
        self.0.borrow_mut().take()
    }
}

pub(crate) fn pending_response(pending: PendingResponse) -> HttpResponse<BoxBody> {
    let mut response = HttpResponse::InternalServerError().body(MISSING_MIDDLEWARE);
    response
        .extensions_mut()
        .insert(PendingResponseHandle::new(pending));
    response
}

/// Actix wrapper for a page awaiting request-aware finalization.
pub struct PendingPage(pub(crate) inertia_core::PendingPage);

impl PendingPage {
    /// Wraps a page produced by a derived typed page.
    pub fn typed(page: impl inertia_core::InertiaPage) -> Self {
        Self(page.into_pending_page())
    }

    /// Converts this wrapper into the core pending page.
    pub fn into_core(self) -> inertia_core::PendingPage {
        self.0
    }
}

impl From<inertia_core::PendingPage> for PendingPage {
    fn from(page: inertia_core::PendingPage) -> Self {
        Self(page)
    }
}

impl Responder for PendingPage {
    type Body = BoxBody;

    fn respond_to(self, _request: &HttpRequest) -> HttpResponse<Self::Body> {
        pending_response(PendingResponse::Page(Box::new(self.0)))
    }
}

/// Actix-compatible untyped page builder.
pub struct DynamicPage(inertia_core::DynamicPage);

impl DynamicPage {
    /// Creates a page for `component`.
    pub fn new(component: impl Into<String>) -> Self {
        Self(inertia_core::DynamicPage::new(component))
    }

    /// Serializes and adds a route prop.
    pub fn prop(mut self, key: impl Into<String>, value: impl Serialize + Send + 'static) -> Self {
        self.0 = self.0.prop(key, value);
        self
    }

    /// Adds a composable asynchronous prop.
    pub fn async_prop<T>(mut self, key: impl Into<String>, prop: inertia_core::Prop<T>) -> Self
    where
        T: Serialize + Send + 'static,
    {
        self.0 = self.0.async_prop(key, prop);
        self
    }

    /// Adds an erased prop generated by the portable `page!` macro.
    #[doc(hidden)]
    pub fn pending_prop(mut self, prop: inertia_core::__private::PendingProp) -> Self {
        self.0 = self.0.pending_prop(prop);
        self
    }

    /// Sets the response status.
    pub fn status(mut self, status: http::StatusCode) -> Self {
        self.0 = self.0.status(status);
        self
    }

    /// Clears encrypted browser history.
    pub fn clear_history(mut self) -> Self {
        self.0 = self.0.clear_history();
        self
    }

    /// Encrypts browser history for this page.
    pub fn encrypt_history(mut self) -> Self {
        self.0 = self.0.encrypt_history();
        self
    }

    /// Preserves the original URL fragment across a redirect.
    pub fn preserve_fragment(mut self) -> Self {
        self.0 = self.0.preserve_fragment();
        self
    }

    /// Attaches a flash value to this page.
    pub fn flash(mut self, key: impl Into<String>, value: impl Serialize) -> Self {
        self.0 = self.0.flash(key, value);
        self
    }

    /// Converts this page into its pending wrapper.
    pub fn into_pending_page(self) -> PendingPage {
        PendingPage(self.0.into_pending_page())
    }
}

impl Responder for DynamicPage {
    type Body = BoxBody;

    fn respond_to(self, request: &HttpRequest) -> HttpResponse<Self::Body> {
        self.into_pending_page().respond_to(request)
    }
}

/// Actix-compatible method-aware redirect.
#[derive(Clone, Debug, PartialEq, Eq)]
pub struct Redirect(inertia_core::Redirect);

impl Redirect {
    /// Creates a redirect to `url`.
    pub fn new(url: impl Into<String>) -> Self {
        Self(inertia_core::Redirect::new(url))
    }

    /// Creates a redirect to a concrete destination.
    pub fn to(url: impl Into<String>) -> Self {
        Self::new(url)
    }

    /// Creates a redirect to the request referrer.
    pub fn back() -> Self {
        Self(inertia_core::Redirect::back())
    }

    /// Creates a redirect to the request referrer with a fallback.
    pub fn back_or(url: impl Into<String>) -> Self {
        Self(inertia_core::Redirect::back_or(url))
    }

    /// Returns the fallback or concrete destination.
    pub fn url(&self) -> &str {
        self.0.url()
    }

    /// Attaches a flash value to the redirect.
    pub fn flash(mut self, key: impl Into<String>, value: impl Serialize) -> Self {
        self.0 = self.0.flash(key, value);
        self
    }

    /// Converts this wrapper to its core representation.
    pub fn into_core(self) -> inertia_core::Redirect {
        self.0
    }
}

impl From<inertia_core::Redirect> for Redirect {
    fn from(redirect: inertia_core::Redirect) -> Self {
        Self(redirect)
    }
}

impl Responder for Redirect {
    type Body = BoxBody;

    fn respond_to(self, _request: &HttpRequest) -> HttpResponse<Self::Body> {
        pending_response(PendingResponse::Redirect(self.0))
    }
}

/// Actix-compatible external location visit.
#[derive(Clone, Debug, PartialEq, Eq)]
pub struct Location(inertia_core::Location);

impl Location {
    /// Creates an external location visit.
    pub fn external(url: impl Into<String>) -> Self {
        Self(inertia_core::Location::external(url))
    }

    /// Creates an external location visit.
    pub fn new(url: impl Into<String>) -> Self {
        Self(inertia_core::Location::new(url))
    }

    /// Returns the destination URL.
    pub fn url(&self) -> &str {
        self.0.url()
    }

    /// Converts this wrapper to its core representation.
    pub fn into_core(self) -> inertia_core::Location {
        self.0
    }
}

impl From<inertia_core::Location> for Location {
    fn from(location: inertia_core::Location) -> Self {
        Self(location)
    }
}

impl Responder for Location {
    type Body = BoxBody;

    fn respond_to(self, _request: &HttpRequest) -> HttpResponse<Self::Body> {
        pending_response(PendingResponse::Location(self.0))
    }
}

/// Constructs an Actix-compatible untyped page with portable prop semantics.
#[macro_export]
macro_rules! page {
    ($component:expr, { $($props:tt)* }) => {{
        let page = $crate::DynamicPage::new($component);
        $crate::__inertia_actix_page_props!(page; $($props)*)
    }};
}

/// Internal token muncher used by [`page!`](crate::page).
#[doc(hidden)]
#[macro_export]
macro_rules! __inertia_actix_page_props {
    ($page:ident;) => { $page };
    ($page:ident; $key:ident : $value:expr $(, $($rest:tt)*)?) => {{
        use $crate::__private::IntoPendingProp as _;
        let mut adapter = $crate::__private::DynamicPropAdapter::new($value);
        let prop = adapter.into_pending_prop(stringify!($key).to_owned());
        let $page = $page.pending_prop(prop);
        $crate::__inertia_actix_page_props!($page; $($($rest)*)?)
    }};
    ($page:ident; $key:ident $(, $($rest:tt)*)?) => {{
        use $crate::__private::IntoPendingProp as _;
        let mut adapter = $crate::__private::DynamicPropAdapter::new($key);
        let prop = adapter.into_pending_prop(stringify!($key).to_owned());
        let $page = $page.pending_prop(prop);
        $crate::__inertia_actix_page_props!($page; $($($rest)*)?)
    }};
}
